/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSupportRouteImport } from './routes/_authed.support'
import { Route as AuthedStudioRouteImport } from './routes/_authed.studio'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedPlannerRouteImport } from './routes/_authed.planner'
import { Route as AuthedKnowledgeBaseRouteImport } from './routes/_authed.knowledge-base'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedCrmRouteImport } from './routes/_authed.crm'
import { Route as AuthedChatRouteImport } from './routes/_authed.chat'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed.analytics'
import { Route as AuthedAgentsRouteImport } from './routes/_authed.agents'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedCrmPipelineRouteImport } from './routes/_authed.crm.pipeline'
import { Route as AuthedCrmLeadsRouteImport } from './routes/_authed.crm.leads'
import { Route as AuthedCrmLeadsLeadIdRouteImport } from './routes/_authed.crm.leads.$leadId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSupportRoute = AuthedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudioRoute = AuthedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlannerRoute = AuthedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKnowledgeBaseRoute = AuthedKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmRoute = AuthedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsRoute = AuthedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrmPipelineRoute = AuthedCrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthedCrmRoute,
} as any)
const AuthedCrmLeadsRoute = AuthedCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthedCrmRoute,
} as any)
const AuthedCrmLeadsLeadIdRoute = AuthedCrmLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AuthedCrmLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthedAdminRoute
  '/agents': typeof AuthedAgentsRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/chat': typeof AuthedChatRoute
  '/crm': typeof AuthedCrmRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/knowledge-base': typeof AuthedKnowledgeBaseRoute
  '/planner': typeof AuthedPlannerRoute
  '/settings': typeof AuthedSettingsRoute
  '/studio': typeof AuthedStudioRoute
  '/support': typeof AuthedSupportRoute
  '/crm/leads': typeof AuthedCrmLeadsRouteWithChildren
  '/crm/pipeline': typeof AuthedCrmPipelineRoute
  '/crm/leads/$leadId': typeof AuthedCrmLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthedAdminRoute
  '/agents': typeof AuthedAgentsRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/chat': typeof AuthedChatRoute
  '/crm': typeof AuthedCrmRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/knowledge-base': typeof AuthedKnowledgeBaseRoute
  '/planner': typeof AuthedPlannerRoute
  '/settings': typeof AuthedSettingsRoute
  '/studio': typeof AuthedStudioRoute
  '/support': typeof AuthedSupportRoute
  '/crm/leads': typeof AuthedCrmLeadsRouteWithChildren
  '/crm/pipeline': typeof AuthedCrmPipelineRoute
  '/crm/leads/$leadId': typeof AuthedCrmLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/agents': typeof AuthedAgentsRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/crm': typeof AuthedCrmRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/knowledge-base': typeof AuthedKnowledgeBaseRoute
  '/_authed/planner': typeof AuthedPlannerRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/studio': typeof AuthedStudioRoute
  '/_authed/support': typeof AuthedSupportRoute
  '/_authed/crm/leads': typeof AuthedCrmLeadsRouteWithChildren
  '/_authed/crm/pipeline': typeof AuthedCrmPipelineRoute
  '/_authed/crm/leads/$leadId': typeof AuthedCrmLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/knowledge-base'
    | '/planner'
    | '/settings'
    | '/studio'
    | '/support'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/knowledge-base'
    | '/planner'
    | '/settings'
    | '/studio'
    | '/support'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/_authed/admin'
    | '/_authed/agents'
    | '/_authed/analytics'
    | '/_authed/chat'
    | '/_authed/crm'
    | '/_authed/dashboard'
    | '/_authed/knowledge-base'
    | '/_authed/planner'
    | '/_authed/settings'
    | '/_authed/studio'
    | '/_authed/support'
    | '/_authed/crm/leads'
    | '/_authed/crm/pipeline'
    | '/_authed/crm/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/support': {
      id: '/_authed/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthedSupportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/studio': {
      id: '/_authed/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthedStudioRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planner': {
      id: '/_authed/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthedPlannerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/knowledge-base': {
      id: '/_authed/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthedKnowledgeBaseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm': {
      id: '/_authed/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthedCrmRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents': {
      id: '/_authed/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthedAgentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crm/pipeline': {
      id: '/_authed/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AuthedCrmPipelineRouteImport
      parentRoute: typeof AuthedCrmRoute
    }
    '/_authed/crm/leads': {
      id: '/_authed/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthedCrmLeadsRouteImport
      parentRoute: typeof AuthedCrmRoute
    }
    '/_authed/crm/leads/$leadId': {
      id: '/_authed/crm/leads/$leadId'
      path: '/$leadId'
      fullPath: '/crm/leads/$leadId'
      preLoaderRoute: typeof AuthedCrmLeadsLeadIdRouteImport
      parentRoute: typeof AuthedCrmLeadsRoute
    }
  }
}

interface AuthedCrmLeadsRouteChildren {
  AuthedCrmLeadsLeadIdRoute: typeof AuthedCrmLeadsLeadIdRoute
}

const AuthedCrmLeadsRouteChildren: AuthedCrmLeadsRouteChildren = {
  AuthedCrmLeadsLeadIdRoute: AuthedCrmLeadsLeadIdRoute,
}

const AuthedCrmLeadsRouteWithChildren = AuthedCrmLeadsRoute._addFileChildren(
  AuthedCrmLeadsRouteChildren,
)

interface AuthedCrmRouteChildren {
  AuthedCrmLeadsRoute: typeof AuthedCrmLeadsRouteWithChildren
  AuthedCrmPipelineRoute: typeof AuthedCrmPipelineRoute
}

const AuthedCrmRouteChildren: AuthedCrmRouteChildren = {
  AuthedCrmLeadsRoute: AuthedCrmLeadsRouteWithChildren,
  AuthedCrmPipelineRoute: AuthedCrmPipelineRoute,
}

const AuthedCrmRouteWithChildren = AuthedCrmRoute._addFileChildren(
  AuthedCrmRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedAgentsRoute: typeof AuthedAgentsRoute
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedCrmRoute: typeof AuthedCrmRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedKnowledgeBaseRoute: typeof AuthedKnowledgeBaseRoute
  AuthedPlannerRoute: typeof AuthedPlannerRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStudioRoute: typeof AuthedStudioRoute
  AuthedSupportRoute: typeof AuthedSupportRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedAgentsRoute: AuthedAgentsRoute,
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedChatRoute: AuthedChatRoute,
  AuthedCrmRoute: AuthedCrmRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedKnowledgeBaseRoute: AuthedKnowledgeBaseRoute,
  AuthedPlannerRoute: AuthedPlannerRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStudioRoute: AuthedStudioRoute,
  AuthedSupportRoute: AuthedSupportRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
